### ISSUE TITLE
記事を公開できない

### ISSUE THREAD

**Issue by deerboy** [uotya/miru#106]
![image](https://user-images.githubusercontent.com/5842851/75858862-58dabb80-5e3c-11ea-979b-8aad38fe51e2.png)

- 公開ボタンを押しても何も起きない
- 画面表示がないので何が起きているのか分からない

**Comment by uotya** [comment]
https://github.com/deerboy/camp-team/issues/90

**Comment by uotya** [comment]
- [x] 無効なURLだった場合のエラーハンドリング
- [ ] 投稿ボタンのdisabled解除
